version: '3'
services:
  ps-harmo-postgres:
    image: postgres:13-alpine
    container_name: ps-harmo-postgres
    environment:
      NODE_ENV: test
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ps-harmo-postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./ps-harmo-postgres-data:/var/lib/postgresql/data
    command: postgres -p ${POSTGRES_PORT}
  ps-harmo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ps-harmo
    depends_on:
      - ps-harmo-postgres
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    working_dir: /usr/src/ps-harmo
    command: bash -c "export DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@ps-harmo-postgres:${POSTGRES_PORT}/${POSTGRES_DATABASE}?schema=public npx prisma generate && npx prisma migrate dev && npm run dev"
    environment:
      NODE_ENV: test
      POSTGRES_HOST: ps-harmo-postgres
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/ps-harmo/src
      - ./prisma:/usr/src/ps-harmo/prisma
    ports:
      - 8080:8080
volumes:
  ps-harmo-postgres-data: